export type TemplateKey =
    | "REACT"
    | "NEXTJS"
    | "EXPRESS"
    | "VUE"
    | "HONO"
    | "ANGULAR"
    | "REACT_TS"
    | "STATIC"
    | "JS"
    | "TYPESCRIPT"
    | "NODE"
    | "NODEMON"
    | "GRAPHQL"
    | "JSON_SERVER"
    | "JSON_GRAPHQL_SERVER"
    | "KOA"
    | "EGG"
    | "RXJS"
    | "SVELTEKIT"
    | "QUASAR"
    | "TRES"
    | "SLIDEV"
    | "BOOTSTRAP_5"
    | "WEB_PLATFORM"
    | "BOLT_VITE_REACT_TS"
    | "BOLT_QWIK"
    | "BOLT_REMOTION"
    | "BOLT_EXPO"
    | "NEXTJS_SHADCN"
    | "VITE_SHADCN"
    | "ASTRO_SHADCN"
    | "GSAP_REACT"
    | "GSAP_VUE"
    | "GSAP_SVELTE"
    | "GSAP_SVELTEKIT"
    | "GSAP_NEXT"
    | "GSAP_NUXT"
    | "HONO_NODEJS"
    | "HONO_NODEJS"
    | "TUTORIALKIT"
    | "BLANK";

export const templatePaths: Record<TemplateKey, string> = {
    REACT: "editron-starters/react",
    NEXTJS: "editron-starters/nextjs",
    EXPRESS: "editron-starters/express-simple",
    VUE: "editron-starters/vue",
    HONO: "editron-starters/hono-nodejs-starter",
    ANGULAR: "editron-starters/angular",
    REACT_TS: "editron-starters/react-ts",
    STATIC: "editron-starters/static",
    JS: "editron-starters/js",
    TYPESCRIPT: "editron-starters/typescript",
    NODE: "editron-starters/node",
    NODEMON: "editron-starters/nodemon",
    GRAPHQL: "editron-starters/graphql",
    JSON_SERVER: "editron-starters/json-server",
    JSON_GRAPHQL_SERVER: "editron-starters/json-graphql-server",
    KOA: "editron-starters/koa",
    EGG: "editron-starters/egg",
    RXJS: "editron-starters/rxjs",
    SVELTEKIT: "editron-starters/sveltekit",
    QUASAR: "editron-starters/quasar",
    TRES: "editron-starters/tres",
    SLIDEV: "editron-starters/slidev",
    BOOTSTRAP_5: "editron-starters/bootstrap-5",
    WEB_PLATFORM: "editron-starters/web-platform",
    BOLT_VITE_REACT_TS: "editron-starters/bolt-vite-react-ts",
    BOLT_QWIK: "editron-starters/bolt-qwik",
    BOLT_REMOTION: "editron-starters/bolt-remotion",
    BOLT_EXPO: "editron-starters/bolt-expo",
    NEXTJS_SHADCN: "editron-starters/nextjs-shadcn",
    VITE_SHADCN: "editron-starters/vite-shadcn",
    ASTRO_SHADCN: "editron-starters/astro-shadcn",
    GSAP_REACT: "editron-starters/gsap-react",
    GSAP_VUE: "editron-starters/gsap-vue",
    GSAP_SVELTE: "editron-starters/gsap-svelte",
    GSAP_SVELTEKIT: "editron-starters/gsap-sveltekit",
    GSAP_NEXT: "editron-starters/gsap-next",
    GSAP_NUXT: "editron-starters/gsap-nuxt",
    HONO_NODEJS: "editron-starters/hono-nodejs-starter",
    TUTORIALKIT: "editron-starters/tutorialkit",
    BLANK: "editron-starters/blank",
};
